### PR TITLE
feat: More es-syntax deprecations

### PR DESCRIPTION
**Pull request by scagood**
I think this is what we need to do for #248

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]

**Comment by aladdin-add** [comment]
is there something needed (as it's marking as a draft)?

**Comment by scagood** [comment]
Oh, sorry, this was because I changed these on my phone, and I did not trust that I had done it right!

I wanted to check on my pc :)

**Comment by aladdin-add** [comment]
well, LGTM! but left it open to you to do a double-check. :)

**Comment by scagood** [comment]
Just checked, and it's all al I'd expect :)
image

**Pull request merged**
