### PR TITLE
feat(node-builtins): Add node globals

### PR DESCRIPTION
**Pull request by scagood**
This is my best effort to transcribe https://nodejs.org/api/globals.html into eslint-plugin-n format 😄

### CODE REVIEW

**Comment by scagood** [comment]
@aladdin-add This is what I meant here https://github.com/eslint-community/eslint-plugin-n/pull/258/files#r1583223678

**Comment by aladdin-add** [comment]
looks great! 👍 

should we remove these from es globals?

**Comment by scagood** [comment]
mmm, I would need to update this script then regenerate the entire file:

https://github.com/eslint-community/eslint-plugin-n/pull/174#issuecomment-1913255700

**Comment by aladdin-add** [comment]
Please feel free to merge as you see fit. 😄

**Pull request merged**
